# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6773f30c294f8fe0b80f84d75eb0de0b5a9334463aec1783d64ddf1c74dc67a32fdcbc5d6fdfb41aa9294e5f63794bf668e7ca0aee6c805237b8a5ccc30e1887

test:
  secret_key_base: ebac2894cdb87a6bcc3a3fa3dc43c28574b1b0204fa6972406b772bef425b8a893d984cae94047818d05ec00c6633d99dcebc45771fbb4d7b0e098c7dca1fdd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
